/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Config.DBConnect;
import Entity.Model_HoaDon;
import Entity.Model_KhuyenMai;
import Entity.Model_Voucher;
import Repository.Reporitories_KhuyenMai;
import Repository.Repositories_Voucher;
import static java.lang.System.load;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class View_KhuyenMai extends javax.swing.JInternalFrame {

    Reporitories_KhuyenMai repo = new Reporitories_KhuyenMai();
    Repositories_Voucher voucher = new Repositories_Voucher();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = 1;

    /**
     * Creates new form View_KhuyenMai
     */
    public View_KhuyenMai() {
        initComponents();

        loadTable(repo.getAll());
        loadTable1(repo.getAll());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        txtPhanTram = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenCT = new javax.swing.JTextField();
        txtMaKm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNgayKT = new javax.swing.JTextField();
        txtNgayBD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        pnlSearch2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimVouCher = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTenVC = new javax.swing.JTextField();
        txtMaVC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNgayBĐVC = new javax.swing.JTextField();
        txtNgayKTVC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_PhanTram = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KM", "Tên CT", "Mô Tả", "Phần Trăm ", "Ngày bắt đầu", "Ngày kết thúc", "Trạng Thái"
            }
        ));
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        jLabel6.setText("Trạng Thái :");

        jLabel7.setText("Phần Trăm :");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "đang áp dụng ", "ngừng áp dụng", "đang áp dụng ", "ngừng áp dụng ", " " }));

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapNhat.setText("Sửa");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jLabel4.setText("Mô Tả :");

        jLabel3.setText("Tên CT :");

        jLabel5.setText("Mã KM :");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Ngày Bắt Đầu :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Ngày Kết Thúc :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhanTram)
                            .addComponent(cboTrangThai, 0, 162, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenCT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(txtMaKm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMoTa))
                                .addGap(24, 24, 24)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnThem)
                .addGap(39, 39, 39)
                .addComponent(btnCapNhat)
                .addGap(29, 29, 29)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPhanTram))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa)
                    .addComponent(btnThem))
                .addGap(439, 439, 439))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Voucher", "Tên Voucher", "Phần Trăm", "Số Lượng", "Ngày Bắt Đầu", "Ngày Kết Thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoucher.setRowHeight(60);
        tblVoucher.setSelectionBackground(new java.awt.Color(255, 102, 204));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVoucher);

        pnlSearch2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        btnTimVouCher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimVouCher.setText("Tìm Voucher");
        btnTimVouCher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimVouCherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch2Layout = new javax.swing.GroupLayout(pnlSearch2);
        pnlSearch2.setLayout(pnlSearch2Layout);
        pnlSearch2Layout.setHorizontalGroup(
            pnlSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimVouCher)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlSearch2Layout.setVerticalGroup(
            pnlSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimVouCher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtMaVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaVCActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã :");

        jLabel9.setText("Tên :");

        jLabel10.setText("Ngày Bắt Đầu :");

        jLabel11.setText("Ngày Kết Thúc :");

        jLabel12.setText("Phần Trăm:");

        jLabel13.setText("%");

        jLabel14.setText("Số Lượng:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaVC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenVC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_PhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgayBĐVC, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtNgayKTVC, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txt_SoLuong))
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtNgayBĐVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(txtNgayKTVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt_PhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Them VC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClear1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear1.setText("CapNhap");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSearch2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnlSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(jButton1)
                    .addComponent(btnClear1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        // TODO add your handling code here:
        int numSelect = tblKhuyenMai.getSelectedRow();
        if (numSelect >= 1) {
            String maKm = tblKhuyenMai.getValueAt(numSelect, 0).toString();
            String tenCT = tblKhuyenMai.getValueAt(numSelect, 1).toString();
            String moTa = tblKhuyenMai.getValueAt(numSelect, 2).toString();
            String phanTram = tblKhuyenMai.getValueAt(numSelect, 3).toString();
            String ngayBD = tblKhuyenMai.getValueAt(numSelect, 4).toString();
            String ngayKT = tblKhuyenMai.getValueAt(numSelect, 5).toString();
            String trangThai = tblKhuyenMai.getValueAt(numSelect, 6).toString();

            txtMaKm.setText(maKm);
            txtTenCT.setText(tenCT);
            txtMoTa.setText(moTa);
            txtPhanTram.setText(phanTram);
            txtNgayBD.setText(ngayBD);
            txtNgayKT.setText(ngayKT);
            cboTrangThai.setSelectedItem(trangThai);
        }


    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased


    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        int numSelect = tblVoucher.getSelectedRow();

        if (numSelect >= 1) {

            String maVC = tblVoucher.getValueAt(numSelect, 0).toString();
            String tenVC = tblVoucher.getValueAt(numSelect, 1).toString();
            String PhanTramGiamGia = tblVoucher.getValueAt(numSelect, 2).toString();
            String SoLuong = tblVoucher.getValueAt(numSelect, 3).toString();
            String ngayBDVC = tblVoucher.getValueAt(numSelect, 4).toString();
            String ngayKTVC = tblVoucher.getValueAt(numSelect, 5).toString();
            txtMaVC.setText(maVC);
            txtTenVC.setText(tenVC);
            txt_PhanTram.setText(PhanTramGiamGia);
            txt_SoLuong.setText(SoLuong);
            txtNgayBĐVC.setText(ngayBDVC);
            txtNgayKTVC.setText(ngayKTVC);

        }

    }//GEN-LAST:event_tblVoucherMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        i = tblKhuyenMai.getSelectedRow();
        Model_KhuyenMai getForm = null;
        int selectedRow = tblKhuyenMai.getSelectedRow();
        if (selectedRow >= 0) {
            getForm = repo.getByMaKM(tblKhuyenMai.getValueAt(selectedRow, 0).toString());
            if (getForm == null) {
                JOptionPane.showMessageDialog(this, "Sản phẩm không tồn tại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String maKm = txtMaKm.getText().trim();
            String tenCT = txtTenCT.getText().trim();
            String moTa = txtMoTa.getText().trim();
            String phanTramStr = txtPhanTram.getText().trim();
            String ngayBDStr = txtNgayBD.getText().trim();
            String ngayKTStr = txtNgayKT.getText().trim();
            int trangThai = cboTrangThai.getSelectedIndex();

            // Kiểm tra xem các trường có bị để trống không
            if (maKm.isEmpty() || tenCT.isEmpty() || moTa.isEmpty() || phanTramStr.isEmpty() || ngayBDStr.isEmpty() || ngayKTStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            getForm.setMakm(maKm);
            getForm.setTenct(tenCT);
            getForm.setMoTa(moTa);
            getForm.setTrangthai(trangThai);
            try {
                // Chuyển đổi dữ liệu đầu vào
                Integer phanTram = Integer.parseInt(phanTramStr);
                getForm.setPhanTram(phanTram);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Phần trăm không hợp lệ.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date ngayBD = sdf.parse(ngayBDStr);
                Date ngayKT = sdf.parse(ngayKTStr);
                getForm.setNgayBatDau(ngayBD);
                getForm.setNgayKetThuc(ngayKT);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ngày không hợp lệ. Vui lòng nhập đúng định dạng yyyy-MM-dd.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                repo.capNhat(getForm);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Update thất bại");
                return;
            }
            JOptionPane.showMessageDialog(this, "Update thành công");
            this.loadTable(repo.getAll());
        } else {

            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng nào");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String maKm = txtMaKm.getText().trim();
        String tenCT = txtTenCT.getText().trim();
        String moTa = txtMoTa.getText().trim();
        String phanTramStr = txtPhanTram.getText().trim();
        String ngayBDStr = txtNgayBD.getText().trim();
        String ngayKTStr = txtNgayKT.getText().trim();
        int trangThai = cboTrangThai.getSelectedIndex();

        // Kiểm tra xem các trường có bị để trống không
        if (maKm.isEmpty() || tenCT.isEmpty() || moTa.isEmpty() || phanTramStr.isEmpty() || ngayBDStr.isEmpty() || ngayKTStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Model_KhuyenMai km = new Model_KhuyenMai();
        km.setMakm(maKm);
        km.setTenct(tenCT);
        km.setMoTa(moTa);
        km.setTrangthai(trangThai);
        try {
            // Chuyển đổi dữ liệu đầu vào
            Integer phanTram = Integer.parseInt(phanTramStr);
            km.setPhanTram(phanTram);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phần trăm không hợp lệ.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date ngayBD = sdf.parse(ngayBDStr);
            Date ngayKT = sdf.parse(ngayKTStr);
            km.setNgayBatDau(ngayBD);
            km.setNgayKetThuc(ngayKT);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày không hợp lệ. Vui lòng nhập đúng định dạng yyyy-MM-dd.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            repo.themkm(km);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            return;
        }
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        this.loadTable(repo.getAll());
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int index = this.tblKhuyenMai.getSelectedRow();
                if (index < 0) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng xóa");
                } else {
                    String MAKM = (String) tblKhuyenMai.getValueAt(this.tblKhuyenMai.getSelectedRow(), 0);
                    System.out.println(MAKM);
                    repo.delete(MAKM);
                    JOptionPane.showMessageDialog(this, "Xoa Thanh Cong Ma KM :" + " " + MAKM);
                    this.loadTable(repo.getAll());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimVouCherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimVouCherActionPerformed
        mol = (DefaultTableModel) tblVoucher.getModel();
        mol.setRowCount(0);
        Model_Voucher voucher = this.voucher.getVoucherByMa(txtTimKiem.getText());
        if (voucher != null) {
            txtMaVC.setText(voucher.getMaVC());
            txtTenVC.setText(voucher.getTenVC());
            txtNgayBĐVC.setText(utils.DateFormater.toString(voucher.getNgayBatDau()));
            txtNgayKTVC.setText(utils.DateFormater.toString(voucher.getNgayBatDau()));

            mol.addRow(new Object[]{
                voucher.getMaVC(),
                voucher.getTenVC(),
                voucher.getPhanTramGiamGia(),
                voucher.getSoLuong(),
                voucher.getNgayBatDau(),
                voucher.getNgayKetThuc()
            });
            tblVoucher.setRowSelectionInterval(0, 0);
        } else {

            txtTenVC.setText("");
            txtNgayBĐVC.setText("");
            txtNgayKTVC.setText("");
            txtMaVC.setText("");
        }
    }//GEN-LAST:event_btnTimVouCherActionPerformed

    private void txtMaVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaVCActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaVC.setText("");
        txtTenVC.setText("");
        txtNgayBĐVC.setText("");
        txtNgayKTVC.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int index = this.tblVoucher.getSelectedRow();
                if (index < 0) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng xóa");
                } else {
                    String MaVC = (String) tblVoucher.getValueAt(this.tblVoucher.getSelectedRow(), 0);
                    System.out.println(MaVC);
                    voucher.delete(MaVC);
                    JOptionPane.showMessageDialog(this, "Xoa Thanh Cong Ma KM :" + " " + MaVC);
                    loadTable1(repo.getAll());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String tenVc = txtTenVC.getText().trim();
        String phantram = txt_PhanTram.getText().trim();
        String soluong = txt_SoLuong.getText().trim();
        
        String ngayBDVc = txtNgayBĐVC.getText().trim();
        String ngayKTVC = txtNgayKTVC.getText().trim();

        // Kiểm tra xem các trường có bị để trống không
        if (phantram.isEmpty() || soluong.isEmpty() ||tenVc.isEmpty() || ngayBDVc.isEmpty() || ngayKTVC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Model_Voucher mvc = new Model_Voucher();
        mvc.setTenVC(tenVc);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            int PHANTRAM = Integer.parseInt(phantram);
            int SOLUONG = Integer.parseInt(soluong);
            Date ngayBD = sdf.parse(ngayBDVc);
            Date ngayKT = sdf.parse(ngayKTVC);
            mvc.setNgayBatDau(ngayBD);
            mvc.setNgayKetThuc(ngayKT);
            mvc.setPhanTramGiamGia(PHANTRAM);
            mvc.setSoLuong(SOLUONG);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày không hợp lệ. Vui lòng nhập đúng định dạng yyyy-MM-dd.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            voucher.themvc(mvc);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            return;
        }
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        this.loadTable1(repo.getAll());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnClear1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimVouCher;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlSearch2;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField txtMaKm;
    private javax.swing.JTextField txtMaVC;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayBĐVC;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtNgayKTVC;
    private javax.swing.JTextField txtPhanTram;
    private javax.swing.JTextField txtTenCT;
    private javax.swing.JTextField txtTenVC;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txt_PhanTram;
    private javax.swing.JTextField txt_SoLuong;
    // End of variables declaration//GEN-END:variables

    private void loadTable(List<Model_KhuyenMai> all) {
        mol = (DefaultTableModel) tblKhuyenMai.getModel();
        mol.setRowCount(0);
        for (Model_KhuyenMai model_KhuyenMai : repo.getAll()) {
            mol.addRow(new Object[]{
                model_KhuyenMai.getMakm(),
                model_KhuyenMai.getTenct(),
                model_KhuyenMai.getMoTa(),
                model_KhuyenMai.getPhanTram(),
                model_KhuyenMai.getNgayBatDau(),
                model_KhuyenMai.getNgayKetThuc(),
                model_KhuyenMai.getTrangthai() == 0 ? "ngừng áp dụng" : "đang áp dụng"});
        }
    }
//    private void loadTableHD(List<Model_HoaDon> all) {
//        mol = (DefaultTableModel) tbl_BangHD.getModel();
//        mol.setRowCount(0);
//        for (Model_HoaDon hd: repo.getlist()) {
//            mol.addRow(new Object[]{
//                hd.getIDHD(),
//                hd.getMa(),
//                hd.getNgayTao(),
//                hd.getTongCong()}
//              );
//                
//        }
    
    private int check() {
        int Check = 1;
        if (txtMaKm.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ma");

        }
        if (txtTenCT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ten");

        }
        if (txtMoTa.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap mo ta ");

        }
        if (txtPhanTram.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap phan tram ");

        }
        if (txtNgayBD.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ngay bat dau ");
        }
        if (txtNgayKT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ngay ket thuc");

        }
        if (txtMaVC.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ma voucher");
        }
        if (txtTenVC.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ten voucher");
        }
        if (txtNgayBĐVC.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ngay bat dau");
        }
        if (txtNgayKTVC.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap ngay ket thuc");

        }

        return Check;
    }

    private void loadTable1(List<Model_KhuyenMai> all) {
        mol = (DefaultTableModel) tblVoucher.getModel();
        mol.setRowCount(0);
        for (Model_Voucher voucher : voucher.getVoucher()) {
            mol.addRow(new Object[]{
                voucher.getMaVC(),
                voucher.getTenVC(),
                voucher.getPhanTramGiamGia(),
                voucher.getSoLuong(),
                voucher.getNgayBatDau(),
                voucher.getNgayKetThuc()
            });
        }
    }

    private String String(JTextField txtTenVC) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
